// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Defines a collection of certificate configurations.
public struct CertificateMap: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A user-defined name of the Certificate Map. Certificate Map names must be
  /// unique globally and match pattern
  /// `projects/*/locations/*/certificateMaps/*`.
  public var name: Swift.String = Swift.String()

  /// One or more paragraphs of text description of a certificate map.
  public var description: Swift.String = Swift.String()

  /// Output only. The creation timestamp of a Certificate Map.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The update timestamp of a Certificate Map.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Set of labels associated with a Certificate Map.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. A list of GCLB targets that use this Certificate Map.
  /// A Target Proxy is only present on this list if it's attached to a
  /// Forwarding Rule.
  public var gclbTargets: [CertificateMap.GclbTarget] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CertificateMap`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CertificateMap().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let gclbTargets = CodingKeys(stringValue: "gclbTargets")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "createTime",
      "updateTime",
      "labels",
      "gclbTargets",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      [CertificateMap.GclbTarget].self, forKey: .gclbTargets)
    {
      self.gclbTargets = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.gclbTargets, forKey: .gclbTargets)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Describes a Target Proxy that uses this Certificate Map.
  public struct GclbTarget: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. IP configurations for this Target Proxy where the
    /// Certificate Map is serving.
    public var ipConfigs: [CertificateMap.GclbTarget.IpConfig] = []

    /// A Target Proxy to which this map is attached to.
    public var targetProxy: TargetProxyOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GclbTarget`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GclbTarget().with { $0.targetHttpsProxy = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let targetHttpsProxy = CodingKeys(stringValue: "targetHttpsProxy")
      static let targetSslProxy = CodingKeys(stringValue: "targetSslProxy")
      static let ipConfigs = CodingKeys(stringValue: "ipConfigs")

      static let _knownKeys: Set<Swift.String> = [
        "targetHttpsProxy",
        "targetSslProxy",
        "ipConfigs",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [CertificateMap.GclbTarget.IpConfig].self, forKey: .ipConfigs)
      {
        self.ipConfigs = value
      }

      var targetProxy: TargetProxyOneOf? = nil
      let targetProxyCheckAndSet = {
        if targetProxy != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'targetProxy'"))
        }
        targetProxy = $0
      }
      if let targetHttpsProxy = try container.decodeIfPresent(
        Swift.String.self, forKey: .targetHttpsProxy)
      {
        try targetProxyCheckAndSet(.targetHttpsProxy(targetHttpsProxy))
      }
      if let targetSslProxy = try container.decodeIfPresent(
        Swift.String.self, forKey: .targetSslProxy)
      {
        try targetProxyCheckAndSet(.targetSslProxy(targetSslProxy))
      }
      self.targetProxy = targetProxy
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.ipConfigs, forKey: .ipConfigs)

      if let choice = self.targetProxy {
        switch choice {
        case .targetHttpsProxy(let value):
          try container.encode(value, forKey: .targetHttpsProxy)
        case .targetSslProxy(let value):
          try container.encode(value, forKey: .targetSslProxy)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Defines IP configuration where this Certificate Map is serving.
    public struct IpConfig: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Output only. An external IP address.
      public var ipAddress: Swift.String = Swift.String()

      /// Output only. Ports.
      public var ports: [Swift.UInt32] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `IpConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = IpConfig().with { $0.ipAddress = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let ipAddress = CodingKeys(stringValue: "ipAddress")
        static let ports = CodingKeys(stringValue: "ports")

        static let _knownKeys: Set<Swift.String> = [
          "ipAddress",
          "ports",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
          self.ipAddress = value
        }
        if let value = try container.decodeIfPresent([Swift.UInt32].self, forKey: .ports) {
          self.ports = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.ipAddress, forKey: .ipAddress)
        try container.encode(self.ports, forKey: .ports)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.certificatemanager.v1.CertificateMap.GclbTarget.IpConfig"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// A Target Proxy to which this map is attached to.
    public enum TargetProxyOneOf: Codable, Equatable, Sendable {
      /// Output only. This field returns the resource name in the following
      /// format:
      /// `//compute.googleapis.com/projects/*/global/targetHttpsProxies/*`.
      case targetHttpsProxy(Swift.String)
      /// Output only. This field returns the resource name in the following
      /// format:
      /// `//compute.googleapis.com/projects/*/global/targetSslProxies/*`.
      case targetSslProxy(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.certificatemanager.v1.CertificateMap.GclbTarget"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.certificatemanager.v1.CertificateMap"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
