// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol CertificateManagerStub: Sendable {
    func listCertificates(
      request: ListCertificatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListCertificatesResponse

    func getCertificate(
      request: GetCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.Certificate

    func createCertificate(
      request: CreateCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateCertificate(
      request: UpdateCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCertificate(
      request: DeleteCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listCertificateMaps(
      request: ListCertificateMapsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListCertificateMapsResponse

    func getCertificateMap(
      request: GetCertificateMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.CertificateMap

    func createCertificateMap(
      request: CreateCertificateMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateCertificateMap(
      request: UpdateCertificateMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCertificateMap(
      request: DeleteCertificateMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listCertificateMapEntries(
      request: ListCertificateMapEntriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListCertificateMapEntriesResponse

    func getCertificateMapEntry(
      request: GetCertificateMapEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.CertificateMapEntry

    func createCertificateMapEntry(
      request: CreateCertificateMapEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateCertificateMapEntry(
      request: UpdateCertificateMapEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCertificateMapEntry(
      request: DeleteCertificateMapEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listDnsAuthorizations(
      request: ListDnsAuthorizationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListDnsAuthorizationsResponse

    func getDnsAuthorization(
      request: GetDnsAuthorizationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.DnsAuthorization

    func createDnsAuthorization(
      request: CreateDnsAuthorizationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateDnsAuthorization(
      request: UpdateDnsAuthorizationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteDnsAuthorization(
      request: DeleteDnsAuthorizationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listCertificateIssuanceConfigs(
      request: ListCertificateIssuanceConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListCertificateIssuanceConfigsResponse

    func getCertificateIssuanceConfig(
      request: GetCertificateIssuanceConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.CertificateIssuanceConfig

    func createCertificateIssuanceConfig(
      request: CreateCertificateIssuanceConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCertificateIssuanceConfig(
      request: DeleteCertificateIssuanceConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listTrustConfigs(
      request: ListTrustConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListTrustConfigsResponse

    func getTrustConfig(
      request: GetTrustConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.TrustConfig

    func createTrustConfig(
      request: CreateTrustConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateTrustConfig(
      request: UpdateTrustConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteTrustConfig(
      request: DeleteTrustConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
