// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class CertificateManagerLogging: CertificateManagerStub {
    let inner: any CertificateManagerStub
    let logger: Logger

    public init(_ inner: any CertificateManagerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-certificatemanager-v1"
      logger[metadataKey: "gcp.client.service"] = "certificatemanager"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CertificateManager"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listCertificates(
      request: ListCertificatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListCertificatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCertificates",
        action: {
          (r: ListCertificatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.ListCertificatesResponse
          in
          return try await self.inner.listCertificates(request: r, options: o)
        })
    }

    public func getCertificate(
      request: GetCertificateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.Certificate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCertificate",
        action: {
          (r: GetCertificateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.Certificate
          in
          return try await self.inner.getCertificate(request: r, options: o)
        })
    }

    public func createCertificate(
      request: CreateCertificateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCertificate",
        action: {
          (r: CreateCertificateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCertificate(request: r, options: o)
        })
    }

    public func updateCertificate(
      request: UpdateCertificateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCertificate",
        action: {
          (r: UpdateCertificateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCertificate(request: r, options: o)
        })
    }

    public func deleteCertificate(
      request: DeleteCertificateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCertificate",
        action: {
          (r: DeleteCertificateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCertificate(request: r, options: o)
        })
    }

    public func listCertificateMaps(
      request: ListCertificateMapsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListCertificateMapsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCertificateMaps",
        action: {
          (r: ListCertificateMapsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.ListCertificateMapsResponse
          in
          return try await self.inner.listCertificateMaps(request: r, options: o)
        })
    }

    public func getCertificateMap(
      request: GetCertificateMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.CertificateMap {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCertificateMap",
        action: {
          (r: GetCertificateMapRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.CertificateMap
          in
          return try await self.inner.getCertificateMap(request: r, options: o)
        })
    }

    public func createCertificateMap(
      request: CreateCertificateMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCertificateMap",
        action: {
          (r: CreateCertificateMapRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCertificateMap(request: r, options: o)
        })
    }

    public func updateCertificateMap(
      request: UpdateCertificateMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCertificateMap",
        action: {
          (r: UpdateCertificateMapRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCertificateMap(request: r, options: o)
        })
    }

    public func deleteCertificateMap(
      request: DeleteCertificateMapRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCertificateMap",
        action: {
          (r: DeleteCertificateMapRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCertificateMap(request: r, options: o)
        })
    }

    public func listCertificateMapEntries(
      request: ListCertificateMapEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListCertificateMapEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCertificateMapEntries",
        action: {
          (r: ListCertificateMapEntriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.ListCertificateMapEntriesResponse
          in
          return try await self.inner.listCertificateMapEntries(request: r, options: o)
        })
    }

    public func getCertificateMapEntry(
      request: GetCertificateMapEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.CertificateMapEntry {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCertificateMapEntry",
        action: {
          (r: GetCertificateMapEntryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.CertificateMapEntry
          in
          return try await self.inner.getCertificateMapEntry(request: r, options: o)
        })
    }

    public func createCertificateMapEntry(
      request: CreateCertificateMapEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCertificateMapEntry",
        action: {
          (r: CreateCertificateMapEntryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCertificateMapEntry(request: r, options: o)
        })
    }

    public func updateCertificateMapEntry(
      request: UpdateCertificateMapEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCertificateMapEntry",
        action: {
          (r: UpdateCertificateMapEntryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCertificateMapEntry(request: r, options: o)
        })
    }

    public func deleteCertificateMapEntry(
      request: DeleteCertificateMapEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCertificateMapEntry",
        action: {
          (r: DeleteCertificateMapEntryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCertificateMapEntry(request: r, options: o)
        })
    }

    public func listDnsAuthorizations(
      request: ListDnsAuthorizationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListDnsAuthorizationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDnsAuthorizations",
        action: {
          (r: ListDnsAuthorizationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.ListDnsAuthorizationsResponse
          in
          return try await self.inner.listDnsAuthorizations(request: r, options: o)
        })
    }

    public func getDnsAuthorization(
      request: GetDnsAuthorizationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.DnsAuthorization {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDnsAuthorization",
        action: {
          (r: GetDnsAuthorizationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.DnsAuthorization
          in
          return try await self.inner.getDnsAuthorization(request: r, options: o)
        })
    }

    public func createDnsAuthorization(
      request: CreateDnsAuthorizationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDnsAuthorization",
        action: {
          (r: CreateDnsAuthorizationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDnsAuthorization(request: r, options: o)
        })
    }

    public func updateDnsAuthorization(
      request: UpdateDnsAuthorizationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDnsAuthorization",
        action: {
          (r: UpdateDnsAuthorizationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDnsAuthorization(request: r, options: o)
        })
    }

    public func deleteDnsAuthorization(
      request: DeleteDnsAuthorizationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDnsAuthorization",
        action: {
          (r: DeleteDnsAuthorizationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDnsAuthorization(request: r, options: o)
        })
    }

    public func listCertificateIssuanceConfigs(
      request: ListCertificateIssuanceConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListCertificateIssuanceConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCertificateIssuanceConfigs",
        action: {
          (r: ListCertificateIssuanceConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.ListCertificateIssuanceConfigsResponse
          in
          return try await self.inner.listCertificateIssuanceConfigs(request: r, options: o)
        })
    }

    public func getCertificateIssuanceConfig(
      request: GetCertificateIssuanceConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.CertificateIssuanceConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCertificateIssuanceConfig",
        action: {
          (r: GetCertificateIssuanceConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.CertificateIssuanceConfig
          in
          return try await self.inner.getCertificateIssuanceConfig(request: r, options: o)
        })
    }

    public func createCertificateIssuanceConfig(
      request: CreateCertificateIssuanceConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCertificateIssuanceConfig",
        action: {
          (r: CreateCertificateIssuanceConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCertificateIssuanceConfig(request: r, options: o)
        })
    }

    public func deleteCertificateIssuanceConfig(
      request: DeleteCertificateIssuanceConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCertificateIssuanceConfig",
        action: {
          (r: DeleteCertificateIssuanceConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCertificateIssuanceConfig(request: r, options: o)
        })
    }

    public func listTrustConfigs(
      request: ListTrustConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.ListTrustConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTrustConfigs",
        action: {
          (r: ListTrustConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.ListTrustConfigsResponse
          in
          return try await self.inner.listTrustConfigs(request: r, options: o)
        })
    }

    public func getTrustConfig(
      request: GetTrustConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCertificateManagerV1.TrustConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTrustConfig",
        action: {
          (r: GetTrustConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCertificateManagerV1.TrustConfig
          in
          return try await self.inner.getTrustConfig(request: r, options: o)
        })
    }

    public func createTrustConfig(
      request: CreateTrustConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTrustConfig",
        action: {
          (r: CreateTrustConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createTrustConfig(request: r, options: o)
        })
    }

    public func updateTrustConfig(
      request: UpdateTrustConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTrustConfig",
        action: {
          (r: UpdateTrustConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateTrustConfig(request: r, options: o)
        })
    }

    public func deleteTrustConfig(
      request: DeleteTrustConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTrustConfig",
        action: {
          (r: DeleteTrustConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteTrustConfig(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
