// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `ListCertificateMapEntries` method.
public struct ListCertificateMapEntriesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project, location and certificate map from which the
  /// certificate map entries should be listed, specified in the format
  /// `projects/*/locations/*/certificateMaps/*`.
  public var parent: Swift.String = Swift.String()

  /// Maximum number of certificate map entries to return. The service may return
  /// fewer than this value.
  /// If unspecified, at most 50 certificate map entries will be returned.
  /// The maximum value is 1000; values above 1000 will be coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The value returned by the last `ListCertificateMapEntriesResponse`.
  /// Indicates that this is a continuation of a prior
  /// `ListCertificateMapEntries` call, and that the system should return the
  /// next page of data.
  public var pageToken: Swift.String = Swift.String()

  /// Filter expression to restrict the returned Certificate Map Entries.
  public var filter: Swift.String = Swift.String()

  /// A list of Certificate Map Entry field names used to specify
  /// the order of the returned results. The default sorting order is ascending.
  /// To specify descending order for a field, add a suffix `" desc"`.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListCertificateMapEntriesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCertificateMapEntriesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.certificatemanager.v1.ListCertificateMapEntriesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
