// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Defines a trust config.
public struct TrustConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A user-defined name of the trust config. TrustConfig names must be
  /// unique globally and match pattern
  /// `projects/*/locations/*/trustConfigs/*`.
  public var name: Swift.String = Swift.String()

  /// Output only. The creation timestamp of a TrustConfig.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last update timestamp of a TrustConfig.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Set of labels associated with a TrustConfig.
  public var labels: [Swift.String: Swift.String] = [:]

  /// One or more paragraphs of text description of a TrustConfig.
  public var description: Swift.String = Swift.String()

  /// This checksum is computed by the server based on the value of other
  /// fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Set of trust stores to perform validation against.
  ///
  /// This field is supported when TrustConfig is configured with Load Balancers,
  /// currently not supported for SPIFFE certificate validation.
  ///
  /// Only one TrustStore specified is currently allowed.
  public var trustStores: [TrustConfig.TrustStore] = []

  /// Initialize a new instance of `TrustConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TrustConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Defines a trust anchor.
  public struct TrustAnchor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var kind: OneOf_Kind? = nil

    /// Initialize a new instance of `TrustAnchor`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TrustAnchor().with { $0.pemCertificate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case pemCertificate = "pemCertificate"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var kind: OneOf_Kind? = nil
      let kindCheckAndSet = {
        if kind != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'kind'"))
        }
        kind = $0
      }
      if let pemCertificate = try container.decodeIfPresent(
        Swift.String.self, forKey: .pemCertificate)
      {
        try kindCheckAndSet(.pemCertificate(pemCertificate))
      }
      self.kind = kind
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.kind {
        switch choice {
        case .pemCertificate(let value):
          try container.encode(value, forKey: .pemCertificate)
        }
      }
    }

    public enum OneOf_Kind: Codable, Equatable, Sendable {
      /// PEM root certificate of the PKI used for validation.
      ///
      /// Each certificate provided in PEM format may occupy up to 5kB.
      case pemCertificate(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.certificatemanager.v1.TrustConfig.TrustAnchor"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines an intermediate CA.
  public struct IntermediateCA: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var kind: OneOf_Kind? = nil

    /// Initialize a new instance of `IntermediateCA`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IntermediateCA().with { $0.pemCertificate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case pemCertificate = "pemCertificate"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var kind: OneOf_Kind? = nil
      let kindCheckAndSet = {
        if kind != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'kind'"))
        }
        kind = $0
      }
      if let pemCertificate = try container.decodeIfPresent(
        Swift.String.self, forKey: .pemCertificate)
      {
        try kindCheckAndSet(.pemCertificate(pemCertificate))
      }
      self.kind = kind
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.kind {
        switch choice {
        case .pemCertificate(let value):
          try container.encode(value, forKey: .pemCertificate)
        }
      }
    }

    public enum OneOf_Kind: Codable, Equatable, Sendable {
      /// PEM intermediate certificate used for building up paths
      /// for validation.
      ///
      /// Each certificate provided in PEM format may occupy up to 5kB.
      case pemCertificate(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.certificatemanager.v1.TrustConfig.IntermediateCA"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines a trust store.
  public struct TrustStore: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// List of Trust Anchors to be used while performing validation
    /// against a given TrustStore.
    public var trustAnchors: [TrustConfig.TrustAnchor] = []

    /// Set of intermediate CA certificates used for the path building
    /// phase of chain validation.
    ///
    /// The field is currently not supported if TrustConfig is used for the
    /// workload certificate feature.
    public var intermediateCas: [TrustConfig.IntermediateCA] = []

    /// Initialize a new instance of `TrustStore`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TrustStore().with { $0.trustAnchors = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.certificatemanager.v1.TrustConfig.TrustStore"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.certificatemanager.v1.TrustConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
